### ISSUE TITLE
[Mod Problem]: unable build basic reactor - graphite block not recognized

### ISSUE THREAD

**Issue by triptaminer** [FTBTeam/FTB-University#186]
* What version of University: v1.1.1 (latest)
* What mod: nuclearcraft 
* Have you made an issue on their issue tracker: no
* If so, link it here: 
* Describe the issue: unable to build very basic reactor. controller doesnt recognize first block (on far left bottom)

with casing block:
[00:22:42] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] Block at -5760, 67, -570 is not connected to this multiblock

with graphite block (not recognized name!):
[00:23:04] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] **tile.nuclearcraft.ingot_block.name** is not a valid block at [-5760, 67, -570]

with air it throws chat info like last one, but blockname is loaded correctly (Air)

**Comment by ThePoleThatFishes** [comment]
NuclearCraft Overhauled has different reactor mechanics compared to standard, so reactors designed with non-overhauled principles don't work in overhauled
Check this video for a guide on overhaul reactors: https://youtu.be/F8I7ar3AB0w (Note that the design presented here is slightly outdated due to rebalancing)

**Comment by triptaminer** [comment]
@ThePoleThatFishes thank you for pointing me to correct mod version. it solves my previous problem, but i found that "slightly outdated design" thing quite soon :D 
i dont think that it is good idea to put new mod without wiki in **learning** modpack :/
