### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-University#2]
Please put all mod suggestions here in the format of:

* Mod Name: 
* Mod Dependencies: 
* Mod License:
* Mod Link:
* Why you want it:

**Comment by enescglyn** [comment]
1- foamfix
2- phospor
3- vanilla fix
(basically every optimization mod it doesnt even have reason every pack has it)

4- quest book
(i want to learn)

5-applied energetiscs 2
(i love wires and this has that and it has storage)

6- jetpack
(i want to fly)

7-every techonology mod (not low tech ones)

also optionally i would like to see the psi mod because you can make your own spells in it

**Comment by enescglyn** [comment]
and please planets when i checked the source code i saw you were talking about planets but anyway its really good to have

**Comment by aaronhowser1** [comment]
@enescglyn this is for AFTER the pack is released, all of those are already in University (except PSI). How did you even find this issue tracker?

**Comment by aaronhowser1** [comment]
I'm removing this to make it into an issue template instead. @enescglyn, you can make a new issue for PSI if you want.
